# Test using the file plugin + volume mount to get console logs from the sidecar
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: console
spec:
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: count
        image: busybox
        args: [/bin/sh, -c,
'
rate=1;
lifetime=-1;

j=0;
while [ ${j} -ne ${lifetime} ];
do
  i=0;
  while [ ${i} -lt ${rate} ];
  do
    echo "$i: $(date)";
    i=$((i+1));
  done;
  sleep 1;
  j=$((j+1));
done
']
      - name: fluentdsidecar
        image: yanmingacr.azurecr.io/fluentdsidecar
        env:
          - name:  APPINSIGHTS_INSTRUMENTATIONKEY
            value: "58e1168f-62bc-4eaf-b546-d1d501190bac"
          - name: NAMESPACE_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: SOURCE_CONTAINER_NAME
            value: "count"
          - name: SEND_SIDECAR_LOG
            value: "false"
          - name: FLUENTD_OPT
            value: "-v"
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: emptydir
          mountPath: /var/fluentdsidecar
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: emptydir
        emptyDir: {}

