# Test using the file plugin + volume mount to get console logs from the sidecar
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: console
spec:
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: count
        image: busybox
        args: [/bin/sh, -c,
                'i=0; while true; do echo "$i: $(date)"; i=$((i+1)); sleep 1; done']
      - name: fluentdsidecar
        image: yanmingacr.azurecr.io/fluentdsidecar
        env:
          - name:  INSTRUMENTATION_KEY
            value: "58e1168f-62bc-4eaf-b546-d1d501190bac"
          - name: NAMESPACE_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: SOURCE_CONTAINER_NAME
            value: "count"
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: emptydir
          mountPath: /var/fluentdsidecar
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: emptydir
        emptyDir: {}

