apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: testsidecar
spec:
  template:
    metadata:
      labels:
        component: testsidecar
    spec:
      containers:
      - name: testhttplog
        image: yanmingacr.azurecr.io/testhttplog
      - name: fluentdsidecar
        image: yanmingacr.azurecr.io/fluentdsidecar
        env:
          - name:  INSTRUMENTATION_KEY
            value: "014dae06-98b6-4fb9-9fa4-abd84d067e9c"
          - name: NAMESPACE_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: SOURCE_CONTAINER_NAME
            value: "testhttplog"

