apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webfrontend
spec:
  template:
    metadata:
      labels:
        app: testsidecar
        component: webfrontend
    spec:
      containers:
      - name: webfrontend
        image: yanmingacr.azurecr.io/webfrontend
      - name: fluentdsidecar
        image: yanmingacr.azurecr.io/fluentdsidecar
        env:
          - name:  APPINSIGHTS_INSTRUMENTATIONKEY
            value: "014dae06-98b6-4fb9-9fa4-abd84d067e9c"
          - name: NAMESPACE_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: SOURCE_CONTAINER_NAME
            value: "testsidecar"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: testsidecar
    component: webfrontend
  name: frontend
spec:
  ports:
  - port: 80
  selector:
    app: testsidecar
    component: webfrontend
  type: LoadBalancer